In [1]:
import tensorflow as tf
from configuration import *
import io_utils

In [2]:
def extract_dataset_colors(dataset_path):
    dataset = tf.keras.utils.image_dataset_from_directory(
        dataset_path,
        labels=None,
        color_mode="rgba",
        batch_size=None,
        image_size=(IMG_SIZE, IMG_SIZE)
    )

    empty_image = tf.zeros([IMG_SIZE, IMG_SIZE, INPUT_CHANNELS])
    image_of_whole_dataset = dataset.reduce(empty_image, lambda acc, image: tf.concat([acc, image], axis=0))

    palette = io_utils.extract_palette(image_of_whole_dataset, INPUT_CHANNELS, None)
    return palette

In [3]:
for folder in DATA_FOLDERS:
    palette = extract_dataset_colors(folder)
    print("Palette for ", folder, ": ", tf.shape(palette))

Found 7296 files belonging to 1 classes.
tf.Tensor(
[[  0   0   0   0]
 [  0   0   0   1]
 [  0   0   0   4]
 ...
 [250 250 250 255]
 [255 255 255 252]
 [255 255 255 255]], shape=(3437, 4), dtype=int32)
